---
apiVersion: v1
kind: Service
metadata:
  name: seata-ha-nacos
  labels:
    app: seata-ha-nacos
spec:
  type: NodePort
  ports:
    - port: 8848
      nodePort: 30848
  selector:
    app: seata-ha

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seata-ha-nacos
spec:
  template:
    metadata:
      labels:
        app: seata-ha-nacos
    spec:
      containers:
        - name: seata-ha-nacos
          imagePullPolicy: IfNotPresent
          image: nacos/nacos-server:latest
          ports:
            - containerPort: 8848
          env:
            - name: MODE
              value: standalone
  selector:
    matchLabels:
      app: seata-ha-nacos