apiVersion: v1
kind: Service
metadata:
  name: seata-ha-server-test
  namespace: default
  labels:
    app.kubernetes.io/name: seata-ha-server-test
spec:
  type: ClusterIP
  ports:
    - port: 8091
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: seata-ha-server-test

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: seata-ha-server-test
  namespace: default
  labels:
    app.kubernetes.io/name: seata-ha-server-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: seata-ha-server-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: seata-ha-server-test
    spec:
      containers:
        - name: seata-ha-server-test
          image: docker.io/seataio/seata-server:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SEATA_CONFIG_NAME
              value: file:/root/seata-config/registry
          ports:
            - name: http
              containerPort: 8091
              protocol: TCP
          volumeMounts:
            - name: seata-config
              mountPath: /root/seata-config
      volumes:
        - name: seata-config
          configMap:
            name: seata-ha-server-test-config


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seata-ha-server-test-config
data:
  registry.conf: |
    registry {
        type = "nacos"
        nacos {
          application = "seata-server"
          serverAddr = "192.168.199.2"
        }
    }
    config {
      type = "nacos"
      nacos {
        serverAddr = "192.168.199.2"
        group = "SEATA_GROUP"
      }
    }